### ISSUE TITLE
混合A*算法中，车辆边界框的顶点坐标计算问题

### ISSUE THREAD

**Issue by shenchenbing** [zhaohaojie1998/Path-Planning#2]
原代码如下：
    def is_collided(self, map_array = MAP.map_array):
        """是否发生碰撞"""
        # 计算车辆的边界框的四个顶点坐标
        cos_ = math.cos(self.yaw)
        sin_ = math.sin(self.yaw)
        LC = CAR_LENGTH/2 * cos_
        LS = CAR_LENGTH/2 * sin_
        WC = CAR_WIDTH/2 * cos_
        WS = CAR_WIDTH/2 * sin_
        x1 = self.x + LC + WS
        y1 = self.y - LS + WC
        x2 = self.x + LC - WS
        y2 = self.y - LS - WC
        x3 = self.x - LC + WS
        y3 = self.y + LS + WC
        x4 = self.x - LC - WS
        y4 = self.y + LS - WC
-------------------------------------------------------------------------
在混合A*算法代码中，规定的是Y轴向下为正，而这里的计算公式里面看上去似乎是按照Y轴向上为正来进行计算的顶点坐标。

正确的计算方式应该是要在LS和WS这两个变量的计算公式的最前面再加一个负号，即：
        LS = - CAR_LENGTH/2 * sin_
        WS = - CAR_WIDTH/2 * sin_

或者更改 x1、x2、x3、x4、y1、y2、y3、y4 的计算公式中的正负号，即：
        x1 = self.x + LC - WS
        y1 = self.y + LS + WC
        x2 = self.x + LC + WS
        y2 = self.y + LS - WC
        x3 = self.x - LC - WS
        y3 = self.y - LS + WC
        x4 = self.x - LC + WS
        y4 = self.y - LS - WC

**Comment by zhaohaojie1998** [comment]
这个不影响，把长款参数对调一下就可以了

**Comment by shenchenbing** [comment]
> 这个不影响，把长款参数对调一下就可以了

如果把长宽参数对调一下，相当于是把车辆旋转了90度，这样还是不对，因为实际需要的是按照水平线（平行于x轴并穿过车辆中心点）做轴对称。

虽然这个问题不影响大部分情况的路径规划，但是通过窄路的时候可能会有问题。
